// samples/darksome.vue
<template>
  <div>
    <h1>Vue Counter App</h1>
    <p>Count: {{ count }}</p>
    <button @click="handleClick">Click me!</button>
  </div>
</template>

<script>
export default {
  data() {
    return {
      count: 0
    };
  },
  methods: {
    handleClick() {
      this.count++;
    }
  }
};
</script>

// samples/darksome-solidjs.jsx
import {createSignal} from 'solid-js';

function App(props) {
  const [count, setCount] = createSignal(0);

  function handleClick() {
    setCount(count() + 1);
  }

  return (
    <div>
      <h1>{props.title}</h1>
      <p>Count: {count()}</p>
      <button onClick={handleClick}>Click me!</button>
    </div>
  );
}

export default App;
